/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnn_core_JNNnative */

#ifndef _Included_jnn_core_JNNnative
#define _Included_jnn_core_JNNnative
#ifdef __cplusplus
extern "C" {
#endif
#undef jnn_core_JNNnative_JNNNative_BACKEND_CPU
#define jnn_core_JNNnative_JNNNative_BACKEND_CPU 1L
/*
 * Class:     jnn_core_JNNnative
 * Method:    setThreads
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnn_core_JNNnative_setThreads
  (JNIEnv *, jclass, jint);

/*
 * Class:     jnn_core_JNNnative
 * Method:    setBackend
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnn_core_JNNnative_setBackend
  (JNIEnv *, jclass, jint);

/*
 * Class:     jnn_core_JNNnative
 * Method:    matmul
 * Signature: ([FIII[FIII[FIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_core_JNNnative_matmul
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jfloatArray, jint, jint, jint, jfloatArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_core_JNNnative
 * Method:    conv2dForward
 * Signature: ([F[F[FZ[FIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_core_JNNnative_conv2dForward
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jboolean, jfloatArray, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_core_JNNnative
 * Method:    conv2dBackward
 * Signature: ([F[F[F[F[FZ[FIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_core_JNNnative_conv2dBackward
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jboolean, jfloatArray, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_core_JNNnative
 * Method:    maxPool2dForward
 * Signature: ([F[FIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_core_JNNnative_maxPool2dForward
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_core_JNNnative
 * Method:    maxPool2dBackward
 * Signature: ([F[F[FIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_core_JNNnative_maxPool2dBackward
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
