/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnn_nativo_JNNNative */

#ifndef _Included_jnn_nativo_JNNNative
#define _Included_jnn_nativo_JNNNative
#ifdef __cplusplus
extern "C" {
#endif
#undef jnn_nativo_JNNNative_JNNNative_BACKEND_CPU
#define jnn_nativo_JNNNative_JNNNative_BACKEND_CPU 1L
/*
 * Class:     jnn_nativo_JNNNative
 * Method:    setThreads
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_setThreads
  (JNIEnv *, jclass, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    setBackend
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_setBackend
  (JNIEnv *, jclass, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    matmul
 * Signature: ([FIII[FIII[FIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_matmul
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jfloatArray, jint, jint, jint, jfloatArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    conv2dForward
 * Signature: ([F[F[FZ[FIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_conv2dForward
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jboolean, jfloatArray, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    conv2dBackward
 * Signature: ([F[F[F[F[FZ[FIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_conv2dBackward
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jboolean, jfloatArray, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    maxPool2dForward
 * Signature: ([F[FIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_maxPool2dForward
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    maxPool2dBackward
 * Signature: ([F[F[FIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_maxPool2dBackward
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
