/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnn_nativo_JNNNative */

#ifndef _Included_jnn_nativo_JNNNative
#define _Included_jnn_nativo_JNNNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnn_nativo_JNNNative
 * Method:    setThreads
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_setThreads
  (JNIEnv *, jclass, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    matmul
 * Signature: ([DIII[DIII[DIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_matmul
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jint, jdoubleArray, jint, jint, jint, jdoubleArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    conv2dForward
 * Signature: ([DI[DI[DIZ[DIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_conv2dForward
  (JNIEnv *, jclass, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jboolean, jdoubleArray, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    conv2dBackward
 * Signature: ([DI[DI[DI[DI[DIZ[DIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_conv2dBackward
  (JNIEnv *, jclass, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jboolean, jdoubleArray, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    maxPool2dForward
 * Signature: ([DI[DIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_maxPool2dForward
  (JNIEnv *, jclass, jdoubleArray, jint, jdoubleArray, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    maxPool2dBackward
 * Signature: ([DI[DI[DIIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_maxPool2dBackward
  (JNIEnv *, jclass, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
