/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnn_nativo_JNNNative */

#ifndef _Included_jnn_nativo_JNNNative
#define _Included_jnn_nativo_JNNNative
#ifdef __cplusplus
extern "C" {
#endif
#undef jnn_nativo_JNNNative_JNNNative_BACKEND_CPU
#define jnn_nativo_JNNNative_JNNNative_BACKEND_CPU 1L
/*
 * Class:     jnn_nativo_JNNNative
 * Method:    setThreads
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_setThreads
  (JNIEnv *, jclass, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    setBackend
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_setBackend
  (JNIEnv *, jclass, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    matmul
 * Signature: ([DIII[DIII[DIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_matmul
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jint, jdoubleArray, jint, jint, jint, jdoubleArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    conv2dForward
 * Signature: ([D[D[DZ[DIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_conv2dForward
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jboolean, jdoubleArray, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    conv2dBackward
 * Signature: ([D[D[D[D[DZ[DIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_conv2dBackward
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jboolean, jdoubleArray, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    maxPool2dForward
 * Signature: ([D[DIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_maxPool2dForward
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jnn_nativo_JNNNative
 * Method:    maxPool2dBackward
 * Signature: ([D[D[DIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jnn_nativo_JNNNative_maxPool2dBackward
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
