/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNNNative */

#ifndef _Included_JNNNative
#define _Included_JNNNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNNNative
 * Method:    matmul
 * Signature: ([DI[DI[DIIII)V
 */
JNIEXPORT void JNICALL Java_JNNNative_matmul
  (JNIEnv *, jclass, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
